### ISSUE TITLE
in the futrue，this will add some featrues？

### ISSUE THREAD

**Issue by catroom** [yarolegovich/DiscreteScrollView#8]
for example ，i can insert a item and delete a item smoothly with long click the item？or add some tranformer？thank

**Comment by yarolegovich** [comment]
Currently only fading in/out on insert/delete is supported. Yes, I am planning to add support for predictive animations. How you delete an item is under your control, you write item adapters and set click listeners. 
For transformer - read the README page.

**Comment by catroom** [comment]
ok。i try some transformer by myself。thanks

**Comment by sevar83** [comment]
Hi @yarolegovich, could you please explain what the predictive animations consists of? I thought they are expected to work out of the box as the library is based on RecyclerView? Are they some work in progress? I'm concerned because I've got `IndexOutOfBoundsException`s when additions / removals of items happen in sequence.

**Comment by yarolegovich** [comment]
Hi, @sevar83. Predictive animations is an extra layout pass to determine positions of appearing/disappearing views. It doesn't happen in my LayoutManager, because `boolean supportsPredictiveAnimations()` is not overriden to return true.
Can you please post the stack trace?

**Comment by sevar83** [comment]
I see. I suppose these animations are beyond my needs then. I'll file an issue right now.
